# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_column_widths <- function(sheetData, sharedStrings, autoColumns, widths, baseFontCharWidth, minW, maxW) {
    .Call('openxlsx_calc_column_widths', PACKAGE = 'openxlsx', sheetData, sharedStrings, autoColumns, widths, baseFontCharWidth, minW, maxW)
}

convert_to_excel_ref <- function(cols, LETTERS) {
    .Call('openxlsx_convert_to_excel_ref', PACKAGE = 'openxlsx', cols, LETTERS)
}

convert_from_excel_ref <- function(x) {
    .Call('openxlsx_convert_from_excel_ref', PACKAGE = 'openxlsx', x)
}

convert_to_excel_ref_expand <- function(cols, LETTERS, rows) {
    .Call('openxlsx_convert_to_excel_ref_expand', PACKAGE = 'openxlsx', cols, LETTERS, rows)
}

isInternalHyperlink <- function(x) {
    .Call('openxlsx_isInternalHyperlink', PACKAGE = 'openxlsx', x)
}

writeFile <- function(parent, xmlText, parentEnd, R_fileName) {
    .Call('openxlsx_writeFile', PACKAGE = 'openxlsx', parent, xmlText, parentEnd, R_fileName)
}

cppReadFile <- function(xmlFile) {
    .Call('openxlsx_cppReadFile', PACKAGE = 'openxlsx', xmlFile)
}

read_file_newline <- function(xmlFile) {
    .Call('openxlsx_read_file_newline', PACKAGE = 'openxlsx', xmlFile)
}

get_letters <- function() {
    .Call('openxlsx_get_letters', PACKAGE = 'openxlsx')
}

get_extLst_Major <- function(xml) {
    .Call('openxlsx_get_extLst_Major', PACKAGE = 'openxlsx', xml)
}

loadworksheets <- function(wb, styleObjects, xmlFiles, is_chart_sheet) {
    .Call('openxlsx_loadworksheets', PACKAGE = 'openxlsx', wb, styleObjects, xmlFiles, is_chart_sheet)
}

getNodes <- function(xml, tagIn) {
    .Call('openxlsx_getNodes', PACKAGE = 'openxlsx', xml, tagIn)
}

getOpenClosedNode <- function(xml, open_tag, close_tag) {
    .Call('openxlsx_getOpenClosedNode', PACKAGE = 'openxlsx', xml, open_tag, close_tag)
}

getAttr <- function(x, tag) {
    .Call('openxlsx_getAttr', PACKAGE = 'openxlsx', x, tag)
}

getChildlessNode_ss <- function(xml, tag) {
    .Call('openxlsx_getChildlessNode_ss', PACKAGE = 'openxlsx', xml, tag)
}

getChildlessNode <- function(xml, tag) {
    .Call('openxlsx_getChildlessNode', PACKAGE = 'openxlsx', xml, tag)
}

get_shared_strings <- function(xmlFile, isFile) {
    .Call('openxlsx_get_shared_strings', PACKAGE = 'openxlsx', xmlFile, isFile)
}

getCellInfo <- function(xmlFile, sharedStrings, skipEmptyRows, startRow, rows, getDates) {
    .Call('openxlsx_getCellInfo', PACKAGE = 'openxlsx', xmlFile, sharedStrings, skipEmptyRows, startRow, rows, getDates)
}

readWorkbook <- function(v, r, string_refs, is_date, nRows, hasColNames, skipEmptyRows, skipEmptyCols, clean_names) {
    .Call('openxlsx_readWorkbook', PACKAGE = 'openxlsx', v, r, string_refs, is_date, nRows, hasColNames, skipEmptyRows, skipEmptyCols, clean_names)
}

calc_number_rows <- function(x, skipEmptyRows) {
    .Call('openxlsx_calc_number_rows', PACKAGE = 'openxlsx', x, skipEmptyRows)
}

unique_cell_append <- function(sheetData, r, newCells) {
    .Call('openxlsx_unique_cell_append', PACKAGE = 'openxlsx', sheetData, r, newCells)
}

buildCellTypes <- function(classes, nRows) {
    .Call('openxlsx_buildCellTypes', PACKAGE = 'openxlsx', classes, nRows)
}

build_cell_merges <- function(comps) {
    .Call('openxlsx_build_cell_merges', PACKAGE = 'openxlsx', comps)
}

buildCellList <- function(r, t, v) {
    .Call('openxlsx_buildCellList', PACKAGE = 'openxlsx', r, t, v)
}

quickBuildCellXML <- function(prior, post, sheetData, rowNumbers, styleInds, R_fileName) {
    .Call('openxlsx_quickBuildCellXML', PACKAGE = 'openxlsx', prior, post, sheetData, rowNumbers, styleInds, R_fileName)
}

quickBuildCellXML2 <- function(prior, post, sheetData, rowNumbers, styleInds, rowHeights, R_fileName) {
    .Call('openxlsx_quickBuildCellXML2', PACKAGE = 'openxlsx', prior, post, sheetData, rowNumbers, styleInds, rowHeights, R_fileName)
}

buildMatrixNumeric <- function(v, rowInd, colInd, colNames, nRows, nCols) {
    .Call('openxlsx_buildMatrixNumeric', PACKAGE = 'openxlsx', v, rowInd, colInd, colNames, nRows, nCols)
}

buildMatrixMixed <- function(v, rowInd, colInd, colNames, nRows, nCols, charCols, dateCols) {
    .Call('openxlsx_buildMatrixMixed', PACKAGE = 'openxlsx', v, rowInd, colInd, colNames, nRows, nCols, charCols, dateCols)
}

matrixRowInds <- function(indices) {
    .Call('openxlsx_matrixRowInds', PACKAGE = 'openxlsx', indices)
}

build_table_xml <- function(table, ref, colNames, showColNames, tableStyle, withFilter) {
    .Call('openxlsx_build_table_xml', PACKAGE = 'openxlsx', table, ref, colNames, showColNames, tableStyle, withFilter)
}

